package ast;

public enum BinaryOperatorType {
    ASSIGMENT, ADDITION, SUBSTRACTION, MULTIPLICATION,
    DIVISION, EQUAL__TO, NOT_EQUAL_TO, GREATER_THAN, LESS_THAN,
    GREATER_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO
}
